from odoo.tests.common import TransactionCase, tagged
from odoo.tools.safe_eval import safe_eval


REGION_ACTIONS = {
    'action_region_north_america': {
        'Canada',
        'United States',
    },
    'action_region_latin_america': {
        'Antigua and Barbuda',
        'Argentina',
        'Bahamas',
        'Barbados',
        'Belize',
        'Bolivia',
        'Brazil',
        'Chile',
        'Colombia',
        'Costa Rica',
        'Cuba',
        'Dominica',
        'Dominican Republic',
        'Ecuador',
        'El Salvador',
        'Grenada',
        'Guatemala',
        'Guyana',
        'Haiti',
        'Honduras',
        'Jamaica',
        'Mexico',
        'Nicaragua',
        'Panama',
        'Paraguay',
        'Peru',
        'Saint Kitts and Nevis',
        'Saint Lucia',
        'Saint Vincent',
        'Suriname',
        'Trinidad and Tobago',
        'Uruguay',
        'Venezuela',
    },
    'action_region_europe': {
        'Albania',
        'Andorra',
        'Austria',
        'Belarus',
        'Belgium',
        'Bosnia and Herzegovina',
        'Bulgaria',
        'Croatia',
        'Cyprus',
        'Czech Republic',
        'Denmark',
        'Estonia',
        'Finland',
        'France',
        'Germany',
        'Greece',
        'Hungary',
        'Iceland',
        'Ireland',
        'Italy',
        'Latvia',
        'Liechtenstein',
        'Lithuania',
        'Luxembourg',
        'Malta',
        'Moldova',
        'Monaco',
        'Montenegro',
        'Netherlands',
        'North Macedonia',
        'Norway',
        'Poland',
        'Portugal',
        'Romania',
        'Russia',
        'San Marino',
        'Serbia',
        'Slovakia',
        'Slovenia',
        'Spain',
        'Sweden',
        'Switzerland',
        'Ukraine',
        'United Kingdom',
        'Vatican City',
    },
    'action_region_middle_east': {
        'Armenia',
        'Azerbaijan',
        'Bahrain',
        'Georgia',
        'Iran',
        'Iraq',
        'Israel',
        'Jordan',
        'Kuwait',
        'Lebanon',
        'Oman',
        'Palestine',
        'Qatar',
        'Saudi Arabia',
        'Syria',
        'Turkey',
        'United Arab Emirates',
        'Yemen',
    },
    'action_region_africa': {
        'Algeria',
        'Angola',
        'Benin',
        'Botswana',
        'Burkina Faso',
        'Burundi',
        'Cabo Verde',
        'Cameroon',
        'Central African Republic',
        'Chad',
        'Comoros',
        'Congo',
        'DR Congo',
        'Djibouti',
        'Egypt',
        'Equatorial Guinea',
        'Eritrea',
        'Eswatini',
        'Ethiopia',
        'Gabon',
        'Gambia',
        'Ghana',
        'Guinea',
        'Guinea-Bissau',
        'Kenya',
        'Lesotho',
        'Liberia',
        'Libya',
        'Madagascar',
        'Malawi',
        'Mali',
        'Mauritania',
        'Mauritius',
        'Morocco',
        'Mozambique',
        'Namibia',
        'Niger',
        'Nigeria',
        'Rwanda',
        'Sao Tome and Principe',
        'Senegal',
        'Seychelles',
        'Sierra Leone',
        'Somalia',
        'South Africa',
        'South Sudan',
        'Sudan',
        'Tanzania',
        'Togo',
        'Tunisia',
        'Uganda',
        'Zambia',
        'Zimbabwe',
    },
    'action_region_south_asia': {
        'Afghanistan',
        'Bangladesh',
        'Bhutan',
        'India',
        'Kazakhstan',
        'Kyrgyzstan',
        'Maldives',
        'Nepal',
        'Pakistan',
        'Sri Lanka',
        'Tajikistan',
        'Turkmenistan',
        'Uzbekistan',
    },
    'action_region_southeast_asia': {
        'Brunei',
        'Cambodia',
        'Indonesia',
        'Laos',
        'Malaysia',
        'Myanmar',
        'Philippines',
        'Singapore',
        'Thailand',
        'Timor-Leste',
        'Vietnam',
    },
    'action_region_east_asia': {
        'China',
        'Japan',
        'Mongolia',
        'North Korea',
        'South Korea',
        'Taiwan',
    },
    'action_region_oceania': {
        'Australia',
        'Fiji',
        'Kiribati',
        'Marshall Islands',
        'Micronesia',
        'Nauru',
        'New Zealand',
        'Palau',
        'Papua New Guinea',
        'Samoa',
        'Solomon Islands',
        'Tonga',
        'Tuvalu',
        'Vanuatu',
    },
}


@tagged('post_install', '-at_install')
class TestCountryCallingGuideRegions(TransactionCase):

    @classmethod
    def setUpClass(cls):
        super().setUpClass()
        cls.Guide = cls.env['x_erp.country_calling_guide']

    def _region_action_countries(self, action_xmlid):
        action = self.env.ref('country_calling_guide.%s' % action_xmlid)
        guides = self.Guide.search(safe_eval(action.domain or '[]'))
        return set(guides.mapped('x_erp_country_name'))

    def test_region_action_domains(self):
        for action_xmlid, expected_countries in REGION_ACTIONS.items():
            self.assertEqual(
                self._region_action_countries(action_xmlid),
                expected_countries,
                '%s should return the expected countries.' % action_xmlid,
            )

    def test_region_actions_cover_all_seed_countries(self):
        all_region_countries = set()
        total_region_entries = 0
        for action_xmlid in REGION_ACTIONS:
            region_countries = self._region_action_countries(action_xmlid)
            total_region_entries += len(region_countries)
            all_region_countries.update(region_countries)
        all_guide_countries = set(self.Guide.search([]).mapped('x_erp_country_name'))
        self.assertEqual(len(all_guide_countries), 195)
        self.assertEqual(total_region_entries, 195)
        self.assertEqual(all_region_countries, all_guide_countries)
